//STEPPER
export const HORIZONTAL_STEP_FORWARD = "HORIZONTAL_STEP_FORWARD";
export const HORIZONTAL_STEP_BACK = "HORIZONTAL_STEP_BACK";
export const VERTICAL_STEP_FORWARD = "VERTICAL_STEP_FORWARD";
export const VERTICAL_STEP_BACK = "VERTICAL_STEP_BACK";

//STEP ONE
export const SEARCHEDPOSITION = "SEARCHEDPOSITION";
export const SHOWRESULTS = "SHOWRESULTS";
export const ACTIVESTEP = "ACTIVESTEP";
export const SALARYTYPE = "SALARYTYPE";
export const SALARYFROM = "SALARYFROM"
export const SALARYTO = "SALARYTO";
export const SALARYTIME = "SALARYTIME";
export const SALARYCONTRACT = "SALARYCONTRACT";
export const ADDRESSCOUNTRY = "ADDRESSCOUNTRY";
export const ADDRESSCITY = "ADDRESSCITY";
export const ADDRESSSTREET = "ADDRESSSTREET";
export const WORKMODE = "WORKMODE";
export const CONTRACTTYPE= "CONTRACTTYPE";
export const WORKMODEL = "WORKMODEL";
export const RECRUITMENTMODE = "RECRUITMENTMODE";
export const ABOUTCOMPANY = "ABOUTCOMPANY";
export const LOGO = "LOGO";
