//STEPPER
export const HORIZONTAL_STEP_FORWARD = "HORIZONTAL_STEP_FORWARD";
export const HORIZONTAL_STEP_BACK = "HORIZONTAL_STEP_BACK";
export const VERTICAL_STEP_FORWARD = "VERTICAL_STEP_FORWARD";
export const VERTICAL_STEP_BACK = "VERTICAL_STEP_BACK";

//STEP ONE
export const SEARCHEDPOSITION = "SEARCHEDPOSITION";
export const SHOWRESULTS = "SHOWRESULTS";
export const ACTIVESTEP = "ACTIVESTEP";
export const SALARYTYPE = "SALARYTYPE";
export const SALARYFROM = "SALARYFROM"
export const SALARYTO = "SALARYTO";
export const SALARYTIME = "SALARYTIME";
export const SALARYCONTRACT = "SALARYCONTRACT";
export const ADDRESSCOUNTRY = "ADDRESSCOUNTRY";
export const ADDRESSCITY = "ADDRESSCITY";
export const ADDRESSSTREET = "ADDRESSSTREET";
export const WORKMODE = "WORKMODE";
export const CONTRACTTYPE= "CONTRACTTYPE";
export const WORKMODEL = "WORKMODEL";
export const RECRUITMENTMODE = "RECRUITMENTMODE";
export const ABOUTCOMPANY = "ABOUTCOMPANY";
export const LOGO = "LOGO";

//STEP TWO
export const RESPONSIBILITIES = "RESPONSIBILITIES";
export const SHOWRESPONSIBILITIESBUTTON = "SHOWRESPONSIBILITIESBUTTON";
export const SHOWQUALIFICATIONFORM = "SHOWQUALIFICATIONFORM";
export const QUALIFICATIONNAME = "QUALIFICATIONNAME";
export const QUALIFICATIONCHARACTERISTIC = "QUALIFICATIONCHARACTERISTIC";
export const QUALIFICATIONEFFECTS = "QUALIFICATIONEFFECTS";
export const COPIEDQUALIFICATIONEFFECTS = "COPIEDQUALIFICATIONEFFECTS";
export const COPIEDSELECTEDTEXT = "COPIEDSELECTEDTEXT";
export const REQUIREMENTS = "REQUIREMENTS";
export const SHOWREQUIREMENTSBUTTON = "SHOWREQUIREMENTSBUTTON";
export const SHOWEDUCATIONFORM = "SHOWEDUCATIONFORM";
export const EDUCATIONLEVEL = "EDUCATIONLEVEL";
export const STUDIESNAME = "STUDIESNAME";
export const STUDIESSTAGE = "STUDIESSTAGE";
export const CERTIFICATENAME = "CERTIFICATENAME";
export const CERTIFICATESTAGE = "CERTIFICATESTAGE";
export const BENEFITS = "BENEFITS";
export const SHOWBENEFITSBUTTON = "SHOWBENEFITSBUTTON";

//STEP
export const RODO = "RODO";

